services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/mean-db?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mongo_data:
