name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute remote SSH commands using    password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/mean-devops-deployment
            git pull origin main
            docker compose pull
            docker compose up -d
